# Generated by Django 4.0.4 on 2022-05-03 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_video_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(default=None)),
                ('profile_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('parent_name', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('datestamp', models.CharField(default=None, max_length=225, null=True)),
                ('timestamp', models.CharField(default=None, max_length=225, null=True)),
                ('Video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.videocomment')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
